name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04  # More stable than ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common zip unzip wget tar openjdk-8-jdk python3 python3-pip

    - name: Install Haxe and Haxelib
      run: |
        wget https://github.com/HaxeFoundation/haxe/releases/download/4.2.5/haxe-4.2.5-linux64.tar.gz
        tar -xzf haxe-4.2.5-linux64.tar.gz
        sudo mv haxe-4.2.5-linux64/* /usr/local/bin
        mkdir ~/haxelib && haxelib setup ~/haxelib
        haxelib install lime
        haxelib install openfl
        haxelib install hxcpp
        haxelib git extension-androidtools https://github.com/jigsaw-4277821/extension-androidtools.git
        haxelib git extension-videoview https://github.com/jigsaw-4277821/extension-videoview.git
        haxelib remove linc_luajit
        haxelib git linc_luajit https://github.com/jigsaw-4277821/linc_luajit.git

    - name: Install Android SDK and NDK r15c
      run: |
        mkdir -p $HOME/android-sdk
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip -d $HOME/android-sdk
        yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses
        $HOME/android-sdk/tools/bin/sdkmanager "platforms;android-29" "build-tools;29.0.3" "ndk;15.2.4203891"

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/15.2.4203891" >> $GITHUB_ENV
        echo "$HOME/android-sdk/tools:$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Lime Setup
      run: haxelib run lime setup android --quiet

    - name: Build APK
      run: haxelib run lime build android -final

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: fnf-psych-engine.apk
        path: export/release/android/bin/app/build/outputs/apk/debug/*.apk
